### ISSUE TITLE
The package doesn't work because i don't know the use field.

### ISSUE THREAD

**Issue by Daveke7** [naifalshaye/nova-text-field-with-icon#1]
Hello.

I installed the package but it doesn't work because i don't know what line to add at the top of the page.
With other packages i have to define the use like this:

```
use Laravel\Nova\Fields\Text;
use Laravel\Nova\Fields\Trix;
use Laravel\Nova\Fields\Date;
```

Could you tell me what to place there?
Thanks!

**Comment by naifalshaye** [comment]
use Naif\TextWithIcon\TextWithIcon;
